# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Service
metadata:
  name: connectivity-monitor-prometheus
  labels: {app: connectivity-monitor-prometheus}
spec:
  selector: {app: connectivity-monitor-prometheus}
  ports: [{port: 9090, name: prometheus}]
  clusterIP: None
