{
 "title": "Golang metrics",
 "tags": [
  "golang",
  "self monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "pod", "query": { "query": "label_values(go_info, pod)" } }
  ]
 },
 "panels": [
  {
   "title": "Readme",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics",
     "type": "text",
     "gridPos": { "h": 22, "w": 17, "x": 0, "y": 1 },
     "options": {
      "content": "The metrics for this dashboard are exposed by [go collector][], the\n[process collector][] and the [http instrumentation][] of the prometheus client\ngolang library.\n\n[go collector]: https://github.com/prometheus/client_golang/blob/6007b2b5cae01203111de55f753e76d8dac1f529/prometheus/go_collector.go#L65-L283\n[process collector]: https://github.com/prometheus/client_golang/blob/babeb356a51b1277535260e0122ad8c46240ab96/prometheus/process_collector.go#L73-L110\n[http instrumentation]: https://github.com/prometheus/client_golang/blob/babeb356a51b1277535260e0122ad8c46240ab96/prometheus/promhttp/http.go#L232-L265\n\n```text\ngo_gc_duration_seconds                     A summary of the pause duration of garbage collection cycles. (summary)\ngo_goroutines                              Number of goroutines that currently exist. (gauge)\ngo_info                                    Information about the Go environment. (gauge)\ngo_memstats_alloc_bytes                    Number of bytes allocated and still in use. (gauge)\ngo_memstats_alloc_bytes_total              Total number of bytes allocated, even if freed. (counter)\ngo_memstats_buck_hash_sys_bytes            Number of bytes used by the profiling bucket hash table. (gauge)\ngo_memstats_frees_total                    Total number of frees. (counter)\ngo_memstats_gc_cpu_fraction                The fraction of this program's available CPU time used by the GC since\n                                           the program started. (gauge)\ngo_memstats_gc_sys_bytes                   Number of bytes used for garbage collection system metadata. (gauge)\ngo_memstats_heap_alloc_bytes               Number of heap bytes allocated and still in use. (gauge)\ngo_memstats_heap_idle_bytes                Number of heap bytes waiting to be used. (gauge)\ngo_memstats_heap_inuse_bytes               Number of heap bytes that are in use. (gauge)\ngo_memstats_heap_objects                   Number of allocated objects. (gauge)\ngo_memstats_heap_released_bytes            Number of heap bytes released to OS. (gauge)\ngo_memstats_heap_sys_bytes                 Number of heap bytes obtained from system. (gauge)\ngo_memstats_last_gc_time_seconds           Number of seconds since 1970 of last garbage collection. (gauge)\ngo_memstats_lookups_total                  Total number of pointer lookups. (counter)\ngo_memstats_mallocs_total                  Total number of mallocs. (counter)\ngo_memstats_mcache_inuse_bytes             Number of bytes in use by mcache structures. (gauge)\ngo_memstats_mcache_sys_bytes               Number of bytes used for mcache structures obtained from system. (gauge)\ngo_memstats_mspan_inuse_bytes              Number of bytes in use by mspan structures. (gauge)\ngo_memstats_mspan_sys_bytes                Number of bytes used for mspan structures obtained from system. (gauge)\ngo_memstats_next_gc_bytes                  Number of heap bytes when next garbage collection will take place. (gauge)\ngo_memstats_other_sys_bytes                Number of bytes used for other system allocations. (gauge)\ngo_memstats_stack_inuse_bytes              Number of bytes in use by the stack allocator. (gauge)\ngo_memstats_stack_sys_bytes                Number of bytes obtained from system for stack allocator. (gauge)\ngo_memstats_sys_bytes                      Number of bytes obtained from system. (gauge)\ngo_threads                                 Number of OS threads created. (gauge)\nprocess_cpu_seconds_total                  Total user and system CPU time spent in seconds. (counter)\nprocess_max_fds                            Maximum number of open file descriptors. (gauge)\nprocess_open_fds                           Number of open file descriptors. (gauge)\nprocess_resident_memory_bytes              Resident memory size in bytes. (gauge)\nprocess_start_time_seconds                 Start time of the process since unix epoch in seconds. (gauge)\nprocess_virtual_memory_bytes               Virtual memory size in bytes. (gauge)\nprocess_virtual_memory_max_bytes           Maximum amount of virtual memory available in bytes. (gauge)\npromhttp_metric_handler_requests_in_flight Current number of scrapes being served. (gauge)\npromhttp_metric_handler_requests_total     Total number of scrapes by HTTP status code. (counter)\n```\n"
     }
    },
    {
     "title": "bytes",
     "type": "table",
     "gridPos": { "h": 22, "w": 7, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (__name__) ({__name__=~\"(go|process)_.+_bytes(_total)?\", pod=~\"$pod\"})"
      }
     ]
    },
    {
     "title": "seconds",
     "type": "table",
     "gridPos": { "h": 17, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (__name__) ({__name__=~\"(go|process)_.+_seconds(_total)?\", pod=~\"$pod\"})"
      }
     ]
    },
    {
     "title": "rest",
     "type": "table",
     "gridPos": { "h": 17, "w": 9, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (__name__) ({__name__=~\"(go|process|promhttp)_.+\",__name__!~\"(go|process)_.+_(seconds|bytes)(_total)?\",pod=~\"$pod\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Favorites",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true
  },
  {
   "title": "User and system CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "mCPU" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{pod=~\"$pod\"}[$__rate_interval]) * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Resident memory size in bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of goroutines that currently exist",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of OS threads created",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of open file descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of bytes allocated and still in use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Information about the Go environment",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "go_info{pod=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "A summary of the pause duration of garbage collection cycles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max by(quantile) (go_gc_duration_seconds{pod=~\"$pod\"})",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Pause duration of garbage collection cycles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_sum{pod=~\"$pod\"}[$__rate_interval]) / rate(go_gc_duration_seconds_count{pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Virtual memory size in bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Maximum amount of virtual memory available in bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_max_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes used by the profiling bucket hash table",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_buck_hash_sys_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Maximum number of open file descriptors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_max_fds{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of mallocs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of frees",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_frees_total{pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of heap bytes allocated and still in use",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of bytes allocated, even if freed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of heap bytes that are in use",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of heap bytes waiting to be used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_idle_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of heap bytes released to OS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_released_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of allocated objects",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_objects{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "The inverse fraction of this program's available CPU time used by the GC since the program started",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "1 / go_memstats_gc_cpu_fraction{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes used for garbage collection system metadata",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_gc_sys_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of seconds since 1970 of last garbage collection",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "dateTimeAsIso" }
     ],
     "targets": [
      {
       "expr": "go_memstats_last_gc_time_seconds{pod=~\"$pod\"} * 1000",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of heap bytes obtained from system",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_sys_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes in use by mcache structures",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mcache_inuse_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Start time of the process since unix epoch in seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
     "yaxes": [
      { "format": "dateTimeAsIso" }
     ],
     "targets": [
      {
       "expr": "process_start_time_seconds{pod=~\"$pod\"} * 1000",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes in use by mspan structures",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total number of pointer lookups",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of heap bytes when next garbage collection will take place",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_next_gc_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes used for mcache structures obtained from system",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mcache_sys_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes in use by the stack allocator",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes obtained from system for stack allocator",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_sys_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes obtained from system",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes used for mspan structures obtained from system",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_sys_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total number of scrapes by HTTP status code",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(promhttp_metric_handler_errors_total{pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} {{code}}"
      }
     ]
    },
    {
     "title": "Number of bytes used for other system allocations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_other_sys_bytes{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current number of scrapes being served",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "promhttp_metric_handler_requests_in_flight{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total number of scrapes by HTTP status code",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(promhttp_metric_handler_requests_total{pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} {{code}}"
      }
     ]
    },
    {
     "title": "Number of memory map areas allocated by the process",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_memory_map_areas{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Maximum number of memory map ares the process can allocate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_memory_map_areas_limit{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}