# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: connectivity-exporter
  namespace: {{ .Release.Namespace }}
  labels: {app: connectivity-exporter}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%

  selector: {matchLabels: {app: connectivity-exporter}}
  template:
    metadata: {labels: {app: connectivity-exporter}}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
    {{- end }}

      containers:

      - name: connectivity-exporter
        image: {{ .Values.image.registry}}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - -r={{ .Values.filteredIPs }}
        - -p={{ .Values.filteredPorts }}
        - -v=0
        - -metrics-addr={{ .Values.metrics.host }}:{{ .Values.metrics.port }}

        securityContext: {capabilities: {add: [NET_ADMIN, SYS_RESOURCE, SYS_ADMIN]}}
        resources:
          requests: {cpu: 200m, memory: 750Mi}
          limits:   {cpu: 2, memory: 3Gi}
        ports: [{name: metrics, containerPort: {{ .Values.metrics.port }}}]
        readinessProbe:
          tcpSocket:
            port: {{ .Values.metrics.port }}
