# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

- name: grafana-reloader
  image: connectivity-monitor-reloader-base:1.0
  command:
  - /bin/sh
  - -c
  - |
#$(sed 's/^/    /' shim/grafana-reloader.sh)
  resources:
    requests: {cpu: 50m, memory: 100Mi}
    limits:   {cpu: 50m, memory: 100Mi}
  volumeMounts:
  - {name: grafana-dashboards-tbz2, mountPath: /var/lib/grafana/dashboards-tbz2}
  - {name: grafana-dashboards,      mountPath: /var/lib/grafana/dashboards}
