# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

- name: image-builder
  image: docker:20.10.5
  command:
  - /bin/sh
  - -c
  - |
    cd /
    echo "$(
      printf "\nCreating a .tgz for building the base image of the reloader containers:\n" >&2
      cd shim
      tar -czv base-image | base64 | tr -d '\n'
    )" | base64 -d | tar -xzv
    cd /base-image
    time docker build -t connectivity-monitor-reloader-base:1.0 .
  resources:
    requests: {cpu: 200m, memory: 100Mi}
    limits:   {cpu: 200m, memory: 100Mi}
  volumeMounts: [{name: docker-socket, mountPath: /var/run/docker.sock}]
