# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

- name: prometheus-config
  configMap:
    name: prometheus-config
    items:
    - {key: prometheus.heredoc.yml, path: prometheus.heredoc.yml}
    - {key: error_budget.heredoc.yml, path: rules/error_budget.heredoc.yml}

- name: prometheus
  emptyDir: {}

- name: metrics
  emptyDir: {}

- name: docker-socket
  hostPath: {path: /var/run/docker.sock, type: Socket}
