# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

- name: grafana
  image: grafana/grafana:7.5.11
  command:
  - /bin/sh
  - -c
  - |
#$(sed 's/^/    /' shim/grafana.sh)
  securityContext: {runAsUser: 0}
  resources:
    requests: {cpu: 100m, memory: 500Mi}
    limits:   {cpu: 100m, memory: 500Mi}
  volumeMounts:
  - {name: grafana-config,     mountPath: /etc/grafana}
  - {name: grafana-dashboards, mountPath: /var/lib/grafana/dashboards}
  - {name: metrics,            mountPath: /metrics}
  ports: [{containerPort: 3000}]
  livenessProbe:
    httpGet:
      path: /healthz
      port: 3000
  readinessProbe:
    httpGet:
      path: /api/health
      port: 3000
  startupProbe:
    httpGet:
      path: /healthz
      port: 3000
    failureThreshold: 30
    periodSeconds: 10
