{
 "title": "Tracking",
 "tags": [ "connectivity monitor" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Heatmap of execution time",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le) (rate(connectivity_exporter_bpf_execution_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "packet rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(connectivity_exporter_bpf_execution_count[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Total processing time (/s)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(connectivity_exporter_bpf_execution_sum[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Avg processing time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(connectivity_exporter_bpf_execution_sum[$__rate_interval]) / rate(connectivity_exporter_bpf_execution_count[$__rate_interval])"
    }
   ]
  }
 ]
}