{
 "title": "Uptime Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": {
     "query": "label_values(downtime:interval, interval)"
    }
   },
   {
    "name": "in",
    "query": {
     "query": "label_values(downtime:in{interval=\"$interval\"}, in)"
    }
   },
   { "name": "sni", "label": "SNI Filter" }
  ]
 },
 "panels": [
  {
   "title": "Total SNIs Tracked",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(downtime{interval=\"$interval\", in=\"$in\", sni=~\".*$sni.*\"}) by (sni))"
    }
   ]
  },
  {
   "title": "SNIs within Error Budget ($in)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(((1-downtime{interval=\"$interval\", in=\"$in\", kind=\"active_failed\", sni=~\".*$sni.*\"})*100) > 99.95)"
    }
   ]
  },
  {
   "title": "SNIs exceeding Error Budget ($in)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(((1-downtime{interval=\"$interval\", in=\"$in\", kind=\"active_failed\", sni=~\".*$sni.*\"})*100) < 99.95)"
    }
   ]
  },
  {
   "title": "Worst Clusters",
   "type": "table",
   "description": "Clusters that have the most downtime.\n\nClicking on the SNI will drill down to the specific SNI dashboard.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - topk(10,downtime{interval=\"$interval\", in=\"$in\", kind=\"active_failed\", sni=~\".*$sni.*\"})) * 100",
     "legendFormat": "{{sni}}"
    }
   ]
  },
  {
   "title": "Clusters with minor issues",
   "type": "table",
   "description": "\"Best\" clusters that are less than 100% uptime.\n\nClicking on the SNI will drill down to the specific SNI dashboard.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10,((1-downtime{interval=\"$interval\", in=\"$in\", kind=\"active_failed\", sni=~\".*$sni.*\"}) * 100) < 100)",
     "legendFormat": "{{sni}}"
    }
   ]
  }
 ]
}