{
 "title": "Uptime2",
 "time": { "from": "now-5m", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": {
     "query": "label_values(downtime:interval, interval)"
    }
   },
   {
    "name": "in",
    "query": {
     "query": "label_values(downtime:in{interval=\"$interval\"}, in)"
    }
   },
   {
    "name": "sni",
    "query": {
     "query": "label_values(downtime:sni{}, sni)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-downtime{interval=\"$interval\", in=~\"$in\", sni=~\"$sni\", kind=\"active_failed\"}) * 100",
     "legendFormat": "{{in}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-downtime{interval=\"$interval\", in=~\"$in\", sni=~\"$sni\", kind=\"active_failed\"}) * 100",
     "legendFormat": "{{in}} {{sni}}"
    },
    { "expr": "vector(99.95)", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "Downtime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "floor(downtime{interval=\"$interval\", in=~\"$in\", sni=~\"$sni\", kind=\"active_failed\"} * 60 * 60)",
     "legendFormat": "{{in}} {{sni}}"
    }
   ]
  },
  {
   "title": "Failed Seconds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed Seconds by Node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max by (node) (connectivity_exporter_seconds_total{sni=~\"$sni\", kind=\"active_failed\"})",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}