{
 "title": "Uptime",
 "time": { "from": "now-5m", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "sni", "query": { "query": "label_values(downtime{}, sni)" } }
  ]
 },
 "panels": [
  {
   "title": "Hour",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-downtime{in=\"hour\", sni=~\"$sni\", kind=\"active_failed\"}) * 100"
    }
   ]
  },
  {
   "title": "Day",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "repeat": "interval",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-downtime{in=\"day\", sni=~\"$sni\", kind=\"active_failed\"}) * 100"
    }
   ]
  },
  {
   "title": "Week",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-downtime{in=\"week\", sni=~\"$sni\", kind=\"active_failed\"}) * 100"
    }
   ]
  },
  {
   "title": "Calendar Month",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-downtime{in=\"calendarmonth\", sni=~\"$sni\", kind=\"active_failed\"}) * 100"
    }
   ]
  },
  {
   "title": "Downtime (hourly)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "floor(downtime{in=\"hour\", sni=~\"$sni\", kind=\"active_failed\"} * 60 * 60)",
     "legendFormat": "{{sni}}"
    }
   ]
  },
  {
   "title": "Downtime (daily)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "floor(downtime{in=\"day\", sni=~\"$sni\", kind=\"active_failed\"} * 60 * 60 * 24)",
     "legendFormat": "{{sni}}"
    }
   ]
  },
  {
   "title": "Downtime (weekly)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "floor(downtime{in=\"week\", sni=~\"$sni\", kind=\"active_failed\"} * 60 * 60 * 24 * 7)",
     "legendFormat": "{{sni}}"
    }
   ]
  },
  {
   "title": "Downtime (montly)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "floor(downtime{in=\"calendarmonth\", sni=~\"$sni\", kind=\"active_failed\"} * 60 * 60 * 24 * scalar(days_in_month(month())))",
     "legendFormat": "{{sni}}"
    }
   ]
  },
  {
   "title": "Uptime (hourly)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-downtime{in=\"hour\", sni=~\"$sni\", kind=\"active_failed\"}) * 100",
     "legendFormat": "{{sni}}"
    },
    { "expr": "vector(99.95)", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "Uptime (daily)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-downtime{in=\"day\", sni=~\"$sni\", kind=\"active_failed\"}) * 100",
     "legendFormat": "{{sni}}"
    },
    { "expr": "vector(99.95)", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "Uptime (weekly)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-downtime{in=\"week\", sni=~\"$sni\", kind=\"active_failed\"}) * 100",
     "legendFormat": "{{sni}}"
    },
    { "expr": "vector(99.95)", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "Uptime (monthly)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-downtime{in=\"calendarmonth\", sni=~\"$sni\", kind=\"active_failed\"}) * 100",
     "legendFormat": "{{sni}}"
    },
    { "expr": "vector(99.95)", "legendFormat": "SLO" }
   ]
  },
  { "title": "Explore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Uptime (daily)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-downtime{in=\"day\", sni=~\"$sni\", kind=\"active_failed\"}) * 100",
     "legendFormat": "{{sni}}:{{in}}"
    },
    { "expr": "vector(99.95)", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "Failed Seconds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed Seconds by Node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max by (node) (connectivity_exporter_seconds_total{sni=~\"$sni\", kind=\"active_failed\"})",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}