{
 "title": "CPU and Memory usage",
 "tags": [
  "memory",
  "cpu",
  "self monitoring",
  "cgroupv1"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(cpu_usage_seconds_total, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(cpu_usage_seconds_total{pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Readme",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics",
     "type": "text",
     "gridPos": { "h": 21, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "The metrics for this dashboard are collected directly from the cgroupfs.\n\nExecutable snippet (extracted from [metrics.sh](https://github.tools.sap/kubernetes/connectivity-monitor/blob/master/connectivity-exporter/metrics.sh)):\n\n```shell\ncd /sys/fs/cgroup || exit 1\nawk 'FILENAME == \"cpuacct/cpuacct.usage\"                {printf \"cpu_usage_seconds_total{} %s\\n\", $1/1e9}\n     FILENAME == \"cpuacct/cpuacct.usage_percpu\"         {for(i=1; i<=NF; i++)\n                                                           printf \"cpu_usage_seconds_total{cpu=\\\"%s\\\"} %s\\n\", i-1, $i/1e9}\n     FILENAME == \"cpu/cpu.cfs_period_us\"                {printf \"cpu_cfs_period_seconds{} %s\\n\",  $1/1e6}\n     FILENAME == \"cpu/cpu.cfs_quota_us\"                 {printf \"cpu_cfs_quota_seconds{} %s\\n\",   $1/1e6}\n     FILENAME == \"cpu/cpu.shares\"                       {printf \"cpu_shares{} %s\\n\",  $1}\n     FILENAME == \"cpu/cpu.stat\"                         {printf \"cpu_stat_%s{} %s\\n\", $1, $2}\n     FILENAME == \"memory/memory.max_usage_in_bytes\"     {printf \"memory_max_usage_in_bytes{} %s\\n\", $1}\n     FILENAME == \"memory/memory.usage_in_bytes\"         {printf \"memory_usage_in_bytes{} %s\\n\",     $1}\n     FILENAME == \"memory/memory.stat\" && $1 !~ /^total/ {printf \"memory_stat_%s{} %s\\n\", $1, $2}' \\\n  cpuacct/cpuacct.usage            \\\n  cpuacct/cpuacct.usage_percpu     \\\n  cpu/cpu.cfs_period_us            \\\n  cpu/cpu.cfs_quota_us             \\\n  cpu/cpu.shares                   \\\n  cpu/cpu.stat                     \\\n  memory/memory.max_usage_in_bytes \\\n  memory/memory.usage_in_bytes     \\\n  memory/memory.stat\n```\n\nExample output:\n\n```prometheus\ncpu_usage_seconds_total{} 18.4423\ncpu_usage_seconds_total{cpu=\"0\"} 11.34\ncpu_usage_seconds_total{cpu=\"1\"} 7.10226\ncpu_cfs_period_seconds{} 0.1\ncpu_cfs_quota_seconds{} 0.02\ncpu_shares{} 204\ncpu_stat_nr_periods{} 12849\ncpu_stat_nr_throttled{} 155\ncpu_stat_throttled_time{} 14073345361 # unit: ns\nmemory_max_usage_in_bytes{} 190087168\nmemory_usage_in_bytes{} 43745280\nmemory_stat_cache{} 14204928\nmemory_stat_rss{} 21487616\nmemory_stat_rss_huge{} 18874368\nmemory_stat_shmem{} 0\nmemory_stat_mapped_file{} 8650752\nmemory_stat_dirty{} 0\nmemory_stat_writeback{} 0\nmemory_stat_swap{} 0\nmemory_stat_pgpgin{} 544731\nmemory_stat_pgpgout{} 540592\nmemory_stat_pgfault{} 1268322\nmemory_stat_pgmajfault{} 0\nmemory_stat_inactive_anon{} 0\nmemory_stat_active_anon{} 21479424\nmemory_stat_inactive_file{} 14057472\nmemory_stat_active_file{} 405504\nmemory_stat_unevictable{} 0\nmemory_stat_hierarchical_memory_limit{} 524288000\nmemory_stat_hierarchical_memsw_limit{} 524288000\n```\n"
     }
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "options": {
    "content": "- the usage of the CPU quota and the memory limit is fairly low in the regular\n  case -> maybe we could use smaller limits\n  - we need to provision the CPU quota and memory limits for the high load scenario (many\n    reconnects during a downtime)\n  - autoscalers are not applicable for this usecase: if the api server is not\n    available, they can't work and the reaction time is far too slow anyways ->\n    some kind of overprovisioning is unavoidable"
   }
  },
  {
   "title": "Total CPU usage vs quota",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "mCPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cpu_usage_seconds_total{pod=~\"$pod\",container=~\"$container\",cpu=\"\"}[$__rate_interval]) * 1000)",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(cpu_cfs_quota_seconds{pod=~\"$pod\",container=~\"$container\"} / cpu_cfs_period_seconds{pod=~\"$pod\",container=~\"$container\"} * 1000)",
     "legendFormat": "quota"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cpu_usage_seconds_total{pod=~\"$pod\",container=~\"$container\",cpu=\"\"}[$__rate_interval]) * 1000) / sum(cpu_cfs_quota_seconds{pod=~\"$pod\",container=~\"$container\"} / cpu_cfs_period_seconds{pod=~\"$pod\",container=~\"$container\"} * 1000) * 100",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Total memory usage vs limit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(memory_usage_in_bytes{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(max_over_time(memory_stat_hierarchical_memory_limit{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(memory_usage_in_bytes{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval])) / sum(max_over_time(memory_stat_hierarchical_memory_limit{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval])) * 100",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "mCPU" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(cpu_usage_seconds_total{pod=~\"$pod\",container=~\"$container\",cpu=\"\"}[$__rate_interval]) * 1000",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    },
    {
     "title": "CPU quota",
     "type": "stat",
     "description": "The CPU quota is enforced in each 100ms period.\n\nAlthough it is not accurate, we can illustrate the CFS quota as a mCPU value. Note that on a multi-core system, the quota enforcement is more complicated than what this simple representation suggests.\n\nI recommend reading this blog post for more details: https://engineering.indeedblog.com/blog/2019/12/unthrottled-fixing-cpu-limits-in-the-cloud/",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "mCPU" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu_cfs_quota_seconds{pod=~\"$pod\",container=~\"$container\"} / cpu_cfs_period_seconds{pod=~\"$pod\",container=~\"$container\"} * 1000",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    },
    {
     "title": "CPU shares",
     "type": "stat",
     "description": "The CPU shares are used to assign CPU time to runnable processes during contention.\n\nThey are only used when the system is saturated.\n\nEach runnable process gets CPU time according to ratio of its share and the sum of the shares of the runnable processes.\n\nProcesses are organised in hierarchies (cgroup) and the shares are enforced on all levels.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "mCPU" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu_shares{pod=~\"$pod\",container=~\"$container\"}",
       "legendFormat": "{{pod}} / {{container}} shares"
      }
     ]
    },
    {
     "title": "CPU usage and quota",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "mCPU" }
     ],
     "targets": [
      {
       "expr": "rate(cpu_usage_seconds_total{pod=~\"$pod\",container=~\"$container\",cpu=\"\"}[$__rate_interval]) * 1000",
       "legendFormat": "{{pod}} / {{container}}"
      },
      {
       "expr": "cpu_cfs_quota_seconds{pod=~\"$pod\",container=~\"$container\"} / cpu_cfs_period_seconds{pod=~\"$pod\",container=~\"$container\"} * 1000",
       "legendFormat": "{{pod}} / {{container}} quota"
      }
     ]
    },
    {
     "title": "CPU usage by core",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "mCPU" }
     ],
     "targets": [
      {
       "expr": "sum by(cpu) (rate(cpu_usage_seconds_total{pod=~\"$pod\",container=~\"$container\", cpu!=\"\"}[$__rate_interval]) * 1000)",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "Used CPU quota enforcement periods",
     "type": "graph",
     "description": "`rate(nr_periods)` number of periods that any thread in the cgroup was runnable during a second\n\n`period` length of the bandwidth control period in seconds (typically 100ms)\n\n`rate(nr_periods) * period` the percentage of the quota enforcement periods with runnable threads from the cgroup\n\n100% means that some of the threads were running in each period. *It does not mean that they were throttled, they might have finished their work within the available quota.*",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(cpu_stat_nr_periods{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval]) * cpu_cfs_period_seconds{pod=~\"$pod\",container=~\"$container\"} * 100",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    },
    {
     "title": "CPU throttled quota enforcement periods",
     "type": "graph",
     "description": "`rate(nr_periods)` number of periods that any thread in the cgroup was runnable in a second\n\n`rate(nr_throttled)` number of runnable periods in which the application used its entire quota and was throttled, in a second\n\n`rate(nr_throttled) / rate(nr_periods)` the percentage of the quota enforcement periods in a second when the threads were runnable but couldn't run because they were throttled by the CPU bandwidth control\n\n*100% means that the application is throttled.* It used all its quota and probably would have needed (much / a bit - we can't know) more CPU time to finish its work. (Probably much higher latency)\n\nValues below 100% mean that the application could finish its work, but needed a bit more wall clock time (hence higher latency) due to quota enforcement.\n\n0% means that the application is not affected by quota enforcement, it could finish its work as fast as it could have finished it without quota enforcement. (same latency)",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(cpu_stat_nr_throttled{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval]) / rate(cpu_stat_nr_periods{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval]) * 100",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    },
    {
     "title": "Rate of CPU throttled time",
     "type": "graph",
     "description": "`throttled_time` sum total amount of time individual threads within the cgroup were throttled",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(cpu_stat_throttled_time{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval]) / 1e9",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage without inactive file",
     "type": "stat",
     "description": "The kubelet excludes inactive_file (i.e. # of bytes of file-backed memory on inactive LRU list) from its calculation as it assumes that memory is reclaimable under pressure.\n\nhttps://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "clamp_min(memory_usage_in_bytes{pod=~\"$pod\",container=~\"$container\"} - memory_stat_inactive_file{pod=~\"$pod\",container=~\"$container\"}, 0)",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "memory_usage_in_bytes{pod=~\"$pod\",container=~\"$container\"}",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    },
    {
     "title": "Max Memory usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "memory_max_usage_in_bytes{pod=~\"$pod\",container=~\"$container\"}",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    },
    {
     "title": "Memory limit",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "memory_stat_hierarchical_memory_limit{pod=~\"$pod\",container=~\"$container\"}",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(memory_usage_in_bytes{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "{{pod}} / {{container}}"
      },
      {
       "expr": "max_over_time(memory_max_usage_in_bytes{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "{{pod}} / {{container}} max"
      },
      {
       "expr": "max_over_time(memory_stat_hierarchical_memory_limit{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "{{pod}} / {{container}} limit"
      }
     ]
    },
    {
     "title": "Available memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(memory_stat_hierarchical_memory_limit{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval]) - max_over_time(memory_usage_in_bytes{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    },
    {
     "title": "Available memory (considering inactive_file as available as well) ",
     "type": "graph",
     "description": "The kubelet excludes inactive_file (i.e. # of bytes of file-backed memory on inactive LRU list) from its calculation as it assumes that memory is reclaimable under pressure.\n\nhttps://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(memory_stat_hierarchical_memory_limit{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval]) - clamp_min(max_over_time(memory_usage_in_bytes{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval]) - max_over_time(memory_stat_inactive_file{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval]), 0)",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    }
   ]
  }
 ]
}