{
 "title": "Failed Seconds",
 "tags": [ "connectivity monitor" ],
 "time": { "from": "now-1h", "to": "now-20s" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(connectivity_exporter_seconds_total, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(connectivity_exporter_seconds_total{pod=~\"$pod\",kind=\"clock\"}[$__range])",
     "legendFormat": "{{kind}}"
    },
    {
     "expr": "increase(connectivity_exporter_seconds_total{pod=~\"$pod\",kind=\"active\"}[$__range])",
     "legendFormat": "{{kind}}"
    },
    {
     "expr": "increase(connectivity_exporter_seconds_total{pod=~\"$pod\",kind=\"active_failed\"}[$__range])",
     "legendFormat": "{{kind}}"
    },
    {
     "expr": "increase(connectivity_exporter_seconds_total{pod=~\"$pod\",kind=\"failed\"}[$__range])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "new connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(connectivity_exporter_connections_total{pod=~\"$pod\",kind=\"successful\"}[$__range])",
     "legendFormat": "{{kind}}"
    },
    {
     "expr": "increase(connectivity_exporter_connections_total{pod=~\"$pod\",kind=\"unacknowledged\"}[$__range])",
     "legendFormat": "{{kind}}"
    },
    {
     "expr": "increase(connectivity_exporter_connections_total{pod=~\"$pod\",kind=\"rejected\"}[$__range])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "packets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(connectivity_exporter_packets_total{pod=~\"$pod\"}[$__range])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "sum of the rate of new connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "c/s" }
   ],
   "targets": [
    {
     "expr": "sum by (kind) (rate(connectivity_exporter_connections_total{pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{kind}}"
    },
    {
     "expr": "sum by (kind) (rate(connectivity_exporter_packets_total{pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{kind}} packets"
    }
   ]
  },
  {
   "title": "failed seconds since start",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "dtdhms" }
   ],
   "targets": [
    {
     "expr": "sum by (kind) (connectivity_exporter_seconds_total{kind=~\"(active_)?failed\",pod=~\"$pod\"})",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "CPU usage (connectivity monitor overhead)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "mCPU" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, instance) (rate(cpu_usage_seconds_total{pod=~\"$pod\",cpu=\"\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage (connectivity monitor overhead)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, instance) (max_over_time(memory_usage_in_bytes{pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}