# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

[server]
router_logging = true
enable_gzip    = true

[auth.anonymous]
enabled  = true
org_role = "Admin"

[log]
mode = "console file"

[log.file]
level = "debug"

[dashboards]
default_home_dashboard_path = "/var/lib/grafana/dashboards/home.json"
