{
 "title": "Memory Stat",
 "tags": [
  "memory",
  "self monitoring",
  "cgroupv1"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(memory_stat_cache, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(memory_stat_cache{pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Readme",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics",
     "type": "text",
     "gridPos": { "h": 32, "w": 14, "x": 0, "y": 1 },
     "options": {
      "content": "The metrics for this dashboard are collected directly from the cgroupfs.\n\nExecutable snippet (extracted from [metrics.sh](https://github.tools.sap/kubernetes/connectivity-monitor/blob/master/connectivity-exporter/metrics.sh)):\n\n```shell\ncd /sys/fs/cgroup || exit 1\nawk '$1 !~ /^total/ {printf \"memory_stat_%s{} %s\\n\", $1, $2}' \\\n  memory/memory.stat\n```\n\nExample output:\n\n```prometheus\nmemory_stat_cache{} 14204928\nmemory_stat_rss{} 21487616\nmemory_stat_rss_huge{} 18874368\nmemory_stat_shmem{} 0\nmemory_stat_mapped_file{} 8650752\nmemory_stat_dirty{} 0\nmemory_stat_writeback{} 0\nmemory_stat_swap{} 0\nmemory_stat_pgpgin{} 544731\nmemory_stat_pgpgout{} 540592\nmemory_stat_pgfault{} 1268322\nmemory_stat_pgmajfault{} 0\nmemory_stat_inactive_anon{} 0\nmemory_stat_active_anon{} 21479424\nmemory_stat_inactive_file{} 14057472\nmemory_stat_active_file{} 405504\nmemory_stat_unevictable{} 0\nmemory_stat_hierarchical_memory_limit{} 524288000\nmemory_stat_hierarchical_memsw_limit{} 524288000\n```\n\nThe memory.stat metrics in the pseudo file `/sys/fs/cgroup/memory/memory.stat` are documented in https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt\n\n```\n# per-memory cgroup local status\ncache         - # of bytes of page cache memory\nrss           - # of bytes of anonymous and swap cache memory (includes transparent hugepages)\nrss_huge      - # of bytes of anonymous transparent hugepages\nmapped_file   - # of bytes of mapped file (includes tmpfs/shmem)\npgpgin        - # of charging events to the memory cgroup. The charging\n                  event happens each time a page is accounted as either mapped\n                  anon page(RSS) or cache page(Page Cache) to the cgroup\npgpgout       - # of uncharging events to the memory cgroup. The uncharging\n                  event happens each time a page is unaccounted from the cgroup\nswap          - # of bytes of swap usage\ndirty         - # of bytes that are waiting to get written back to the disk\nwriteback     - # of bytes of file/anon cache that are queued for syncing to disk\ninactive_anon - # of bytes of anonymous and swap cache memory on inactive LRU list\nactive_anon   - # of bytes of anonymous and swap cache memory on active LRU list\ninactive_file - # of bytes of file-backed memory on inactive LRU list\nactive_file   - # of bytes of file-backed memory on active LRU list\nunevictable   - # of bytes of memory that cannot be reclaimed (mlocked etc)\n```\n\n```\n# status considering hierarchy (see memory.use_hierarchy settings)\n\nhierarchical_memory_limit - # of bytes of memory limit with regard to hierarchy\n                              under which the memory cgroup is\nhierarchical_memsw_limit  - # of bytes of memory+swap limit with regard to\n                              hierarchy under which memory cgroup is\n```\n"
     }
    },
    {
     "title": "bytes",
     "type": "table",
     "gridPos": { "h": 18, "w": 10, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (__name__) ({__name__=~\"memory_stat_.+\",__name__!~\"memory_stat_pgpg(in|out)\",__name__!~\"memory_stat_.+fault\",pod=~\"$pod\",container=~\"$container\"})"
      }
     ]
    },
    {
     "title": "events",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (__name__) ({__name__=~\"memory_stat_(pgpg(in|out)|.+fault)\",pod=~\"$pod\",container=~\"$container\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache RSS mapped_file unevictable shmem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "cache - # of bytes of page cache memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "memory_stat_cache{pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "mapped_file   - # of bytes of mapped file (includes tmpfs/shmem)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "memory_stat_mapped_file{pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "rss           - # of bytes of anonymous and swap cache memory (includes transparent hugepages)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "memory_stat_rss{pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "rss_huge      - # of bytes of anonymous transparent hugepages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "memory_stat_rss_huge{pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "unevictable   - # of bytes of memory that cannot be reclaimed (mlocked etc)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "memory_stat_unevictable{pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "Shmem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "memory_stat_shmem", "legendFormat": "{{pod}} / {{container}}" }
   ]
  },
  { "title": "File / Anon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "active_anon   - # of bytes of anonymous and swap cache memory on active LRU list",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "memory_stat_active_anon{pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "inactive_anon - # of bytes of anonymous and swap cache memory on inactive LRU list",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "memory_stat_inactive_anon{pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "active_file   - # of bytes of file-backed memory on active LRU list",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "memory_stat_active_file{pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "inactive_file - # of bytes of file-backed memory on inactive LRU list",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "memory_stat_inactive_file{pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "writeback     - # of bytes of file/anon cache that are queued for syncing to disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "memory_stat_writeback{pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "dirty         - # of bytes that are waiting to get written back to the disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "memory_stat_dirty{pod=~\"$pod\",container=~\"$container\"}",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "pgpgin        - rate of charging events to the memory cgroup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "e/s" }
   ],
   "targets": [
    {
     "expr": "rate(memory_stat_pgpgin{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval])",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "pgpgout - rate of uncharging events to the memory cgroup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "e/s" }
   ],
   "targets": [
    {
     "expr": "rate(memory_stat_pgpgout{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval])",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "Page fault",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(memory_stat_pgfault[$__rate_interval])",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "Major Page fault",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(memory_stat_pgmajfault[$__rate_interval])",
     "legendFormat": "{{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "swap          - # of bytes of swap usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "memory_stat_swap{pod=~\"$pod\",container=~\"$container\"}",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "hierarchical_memory_limit - # of bytes of memory limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "memory_stat_hierarchical_memory_limit{pod=~\"$pod\",container=~\"$container\"}",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    },
    {
     "title": "hierarchical_memsw_limit  - # of bytes of memory+swap limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "memory_stat_hierarchical_memsw_limit{pod=~\"$pod\",container=~\"$container\"}",
       "legendFormat": "{{pod}} / {{container}}"
      }
     ]
    }
   ]
  }
 ]
}