# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

- name: prometheus-reloader
  image: alpine:3.13.2
  command:
  - /bin/sh
  - -c
  - |
#$(sed 's/^/    /' shim/prometheus-reloader.sh)
  resources:
    requests: {cpu: 50m, memory: 100Mi}
    limits:   {cpu: 50m, memory: 100Mi}
  volumeMounts:
  - {name: prometheus-config,    mountPath: /etc/prometheus-config}
  - {name: prometheus,           mountPath: /etc/prometheus}
  - {name: connectivity-monitor, mountPath: /var/lib/prometheus, subPath: prometheus}
