# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata: {name: connectivity-monitor}
  spec:
    accessModes: [ReadWriteOnce]
    resources: {requests: {storage: 1Gi}}
    volumeMode: Filesystem
