# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

alertmanager:
  enabled: false

coreDns:
  enabled: false

defaultRules:
  create: false

grafana:
  image:
    repository: grafana/grafana
    tag: 7.5.13
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
  defaultDashboardsEnabled: false

kubeApiServer:
  enabled: false

kubeControllerManager:
  enabled: false

kubeDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

kubeScheduler:
  enabled: false

kubeStateMetrics:
  enabled: false

kubelet:
  enabled: false

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: default
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

nodeExporter:
  enabled: false
