# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
- name:      prometheus
  type:      prometheus
  access:    proxy
  isDefault: true
  editable:  true
  url:       http://connectivity-monitor-prometheus:9090
  jsonData:
    timeInterval: 2s
